"""empty message

Revision ID: 6064fca396c8
Revises: 
Create Date: 2019-09-21 02:46:54.856756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6064fca396c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('mal_score', sa.String(length=4), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_mal_id'), 'anime', ['mal_id'], unique=True)
    op.create_table('top_anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('mal_score', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_anime_mal_id'), 'top_anime', ['mal_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media', sa.String(length=7), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('user_score', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_top_anime_mal_id'), table_name='top_anime')
    op.drop_table('top_anime')
    op.drop_index(op.f('ix_anime_mal_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
