"""added MAL_database db

Revision ID: 7fd462e440e5
Revises: d0cd562238ec
Create Date: 2019-09-25 22:36:44.352279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd462e440e5'
down_revision = 'd0cd562238ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MAL__database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('anime_type', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('mal_url', sa.String(length=256), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('mal_score', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MAL__database_image_url'), 'MAL__database', ['image_url'], unique=False)
    op.create_index(op.f('ix_MAL__database_mal_id'), 'MAL__database', ['mal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MAL__database_mal_id'), table_name='MAL__database')
    op.drop_index(op.f('ix_MAL__database_image_url'), table_name='MAL__database')
    op.drop_table('MAL__database')
    # ### end Alembic commands ###
