"""empty message

Revision ID: d0cd562238ec
Revises: 6064fca396c8
Create Date: 2019-09-25 17:32:09.112502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0cd562238ec'
down_revision = '6064fca396c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('status', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'status')
    # ### end Alembic commands ###
